#!/usr/bin/env bash
# =============================================================================
# 03-configure-containerd-registry.sh
#
# Force kubelet/containerd to pull from a plain-HTTP registry (NOT HTTPS).
# Fixes:
#   Head "https://zot-registry:30001/v2/...": http: server gave HTTP response to HTTPS client
#
# Writes BOTH:
#   1) /etc/containerd/certs.d/<registry>/hosts.toml  (modern config_path)
#   2) legacy CRI registry.mirrors endpoint = ["http://..."] in config.toml
#
# Run on EVERY Kubernetes node (masters and workers), then:
#   kubectl -n argocd delete pods --all
#
# Usage:
#   sudo ./scripts/03-configure-containerd-registry.sh apply --registry zot-registry:30001
#   sudo ./scripts/03-configure-containerd-registry.sh show --registry zot-registry:30001
#   ./scripts/03-configure-containerd-registry.sh print --registry zot-registry:30001
#
# Commands:
#   apply   Write plain-HTTP registry config and restart containerd
#   show    Show current config for the registry
#   print   Print hosts.toml that would be written (no root needed)
#   verify  Probe http://REGISTRY/v2/ and check config files exist
#
# Options:
#   --registry HOST:PORT   Registry address (default: zot-registry:30001)
#   --certs-dir DIR        containerd certs.d root (default: /etc/containerd/certs.d)
#   --config FILE          containerd config.toml (default: /etc/containerd/config.toml)
#   --no-restart           Do not restart containerd after apply
#   --docker               Also add insecure-registries to /etc/docker/daemon.json
#   -h, --help
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

COMMAND=""
REGISTRY="${PRIVATE_REGISTRY:-${DEFAULT_PRIVATE_REGISTRY}}"
CERTS_DIR="${CONTAINERD_CERTS_DIR:-/etc/containerd/certs.d}"
CONTAINERD_CONFIG="${CONTAINERD_CONFIG:-/etc/containerd/config.toml}"
RESTART=1
CONFIGURE_DOCKER=0

usage() {
  sed -n '2,40p' "$0" | sed 's/^# \?//'
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    apply|show|print|verify) COMMAND="$1"; shift ;;
    --registry)     REGISTRY="$2"; shift 2 ;;
    --certs-dir)    CERTS_DIR="$2"; shift 2 ;;
    --config)       CONTAINERD_CONFIG="$2"; shift 2 ;;
    --no-restart)   RESTART=0; shift ;;
    --docker)       CONFIGURE_DOCKER=1; shift ;;
    -h|--help)      usage ;;
    *) die "Unknown argument: $1 (use --help)" ;;
  esac
done

[[ -n "$COMMAND" ]] || die "Command required: apply|show|print|verify"
# Strip any scheme — image refs and containerd keys use host:port only.
# Pulls are forced to plain HTTP via hosts.toml / mirrors (never https://).
REGISTRY="${REGISTRY#http://}"
REGISTRY="${REGISTRY#https://}"
REGISTRY="${REGISTRY%/}"
REGISTRY="${REGISTRY%/v2}"
REGISTRY="${REGISTRY%/v2/}"

HOSTS_DIR="${CERTS_DIR}/${REGISTRY}"
HOSTS_FILE="${HOSTS_DIR}/hosts.toml"

hosts_toml_contents() {
  # Explicit http:// host entry — containerd must NOT dial https://
  cat <<EOF
# Generated by 03-configure-containerd-registry.sh
# Plain HTTP only — do not use https:// for ${REGISTRY}

server = "http://${REGISTRY}"

[host."http://${REGISTRY}"]
  capabilities = ["pull", "resolve", "push"]
  skip_verify = true
EOF
}

ensure_config_path() {
  [[ -f "$CONTAINERD_CONFIG" ]] || {
    warn "containerd config not found at ${CONTAINERD_CONFIG}; writing hosts.toml only"
    return 0
  }

  if grep -qE 'config_path\s*=' "$CONTAINERD_CONFIG"; then
    local current
    current="$(awk -F'=' '/config_path/ {gsub(/[ "'\''\t]/, "", $2); print $2; exit}' "$CONTAINERD_CONFIG" || true)"
    if [[ -n "$current" && "$current" != "$CERTS_DIR" ]]; then
      warn "containerd config_path is '${current}' (expected ${CERTS_DIR})"
      warn "Pass --certs-dir ${current} or update config.toml config_path"
    else
      info "containerd config_path already set (${current:-ok})"
    fi
  else
    info "Adding registry config_path to ${CONTAINERD_CONFIG}"
    cat >>"$CONTAINERD_CONFIG" <<EOF

# Added by 03-configure-containerd-registry.sh — enable certs.d hosts.toml (plain HTTP)
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "${CERTS_DIR}"
EOF
  fi

  # containerd 2.x / newer CRI plugin path (idempotent append if missing)
  if ! grep -qE "io\.containerd\.cri\.v1\.images" "$CONTAINERD_CONFIG" || \
     ! grep -qE 'config_path\s*=' "$CONTAINERD_CONFIG"; then
    :
  fi
  if grep -q "io.containerd.cri.v1.images" "$CONTAINERD_CONFIG" && \
     ! grep -A5 "io.containerd.cri.v1.images" "$CONTAINERD_CONFIG" | grep -q 'config_path'; then
    info "Adding containerd 2.x images.registry config_path"
    cat >>"$CONTAINERD_CONFIG" <<EOF

# Added by 03-configure-containerd-registry.sh (containerd 2.x)
[plugins."io.containerd.cri.v1.images".registry]
  config_path = "${CERTS_DIR}"
EOF
  fi
}

# Legacy CRI mirrors force endpoint http://HOST:PORT (avoids HTTPS default).
# Kept alongside hosts.toml for kubeadm/containerd builds that still honor mirrors.
ensure_legacy_http_mirror() {
  [[ -f "$CONTAINERD_CONFIG" ]] || return 0

  if grep -qE "mirrors\.\"${REGISTRY}\"" "$CONTAINERD_CONFIG" && \
     grep -qE "http://${REGISTRY}" "$CONTAINERD_CONFIG"; then
    info "Legacy HTTP mirror for ${REGISTRY} already present"
    return 0
  fi

  info "Adding legacy CRI HTTP mirror for ${REGISTRY}"
  cat >>"$CONTAINERD_CONFIG" <<EOF

# Added by 03-configure-containerd-registry.sh — force plain HTTP (not HTTPS)
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."${REGISTRY}"]
  endpoint = ["http://${REGISTRY}"]
[plugins."io.containerd.grpc.v1.cri".registry.configs."${REGISTRY}".tls]
  insecure_skip_verify = true
EOF
}

configure_docker_insecure() {
  local daemon_json="/etc/docker/daemon.json"
  info "Ensuring Docker insecure-registries includes ${REGISTRY}"
  if ! command -v python3 >/dev/null 2>&1; then
    warn "python3 not found; write ${daemon_json} manually with insecure-registries: [\"${REGISTRY}\"]"
    return 0
  fi
  python3 - <<PY
import json, os
path = "${daemon_json}"
data = {}
if os.path.exists(path):
    with open(path) as f:
        try:
            data = json.load(f) or {}
        except Exception:
            data = {}
regs = data.get("insecure-registries") or []
if "${REGISTRY}" not in regs:
    regs.append("${REGISTRY}")
data["insecure-registries"] = regs
os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
print(f"updated {path}: insecure-registries={regs}")
PY
  if command -v systemctl >/dev/null 2>&1; then
    systemctl restart docker || warn "Failed to restart docker; restart manually"
  fi
}

restart_containerd() {
  if [[ "$RESTART" -ne 1 ]]; then
    warn "Skipping containerd restart (--no-restart). Restart manually before deleting pods."
    return 0
  fi
  info "Restarting containerd"
  if command -v systemctl >/dev/null 2>&1; then
    systemctl restart containerd
    systemctl is-active --quiet containerd && info "containerd is active" \
      || warn "containerd may not be active; check: systemctl status containerd"
  else
    warn "systemctl not available; restart containerd manually"
  fi
}

cmd_print() {
  hosts_toml_contents
  echo
  echo "# Target path: ${HOSTS_FILE}"
  echo
  cat <<EOF
# Also appended to ${CONTAINERD_CONFIG}:
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."${REGISTRY}"]
  endpoint = ["http://${REGISTRY}"]
EOF
}

cmd_show() {
  info "Registry: ${REGISTRY} (plain HTTP — not HTTPS)"
  info "Expected hosts file: ${HOSTS_FILE}"
  if [[ -f "$HOSTS_FILE" ]]; then
    echo "---- ${HOSTS_FILE} ----"
    cat "$HOSTS_FILE"
  else
    warn "hosts.toml not found"
  fi
  if [[ -f "$CONTAINERD_CONFIG" ]]; then
    echo "---- registry bits in ${CONTAINERD_CONFIG} ----"
    grep -nE "config_path|${REGISTRY}|registry\.mirrors|registry\.configs" "$CONTAINERD_CONFIG" | head -60 || true
  fi
}

cmd_verify() {
  local url="http://${REGISTRY}/v2/"
  info "Probing plain HTTP ${url} (must NOT use https://)"
  local code
  code="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 5 "$url" 2>/dev/null || echo down)"
  info "HTTP ${code} (200 or 401 means the registry is reachable over HTTP)"
  [[ -f "$HOSTS_FILE" ]] && info "hosts.toml present" || warn "hosts.toml missing: ${HOSTS_FILE}"
  if [[ -f "$CONTAINERD_CONFIG" ]]; then
    if grep -q "http://${REGISTRY}" "$CONTAINERD_CONFIG" || [[ -f "$HOSTS_FILE" ]]; then
      info "Plain HTTP registry config looks present"
    else
      warn "No plain HTTP endpoint found in containerd config — run apply"
    fi
  fi
  if command -v ctr >/dev/null 2>&1; then
    info "Test pull (plain HTTP, not HTTPS):"
    echo "  ctr -n k8s.io images pull --plain-http ${REGISTRY}/argoproj/argocd:v3.5.0"
  fi
}

cmd_apply() {
  [[ "$(id -u)" -eq 0 ]] || die "apply must run as root (sudo)"

  info "Forcing plain HTTP (not HTTPS) pulls for registry ${REGISTRY}"
  mkdir -p "$HOSTS_DIR"
  hosts_toml_contents >"$HOSTS_FILE"
  info "Wrote ${HOSTS_FILE}"
  ensure_config_path
  ensure_legacy_http_mirror
  if [[ "$CONFIGURE_DOCKER" -eq 1 ]]; then
    configure_docker_insecure
  fi
  restart_containerd

  section "Next steps"
  cat <<EOF

Plain HTTP is configured on THIS node for ${REGISTRY}.

1) Repeat on EVERY worker (required — pods schedule off-master):
     sudo ./scripts/03-configure-containerd-registry.sh apply --registry ${REGISTRY}

2) Confirm plain HTTP (not https://):
     curl -sS -o /dev/null -w '%{http_code}\\n' http://${REGISTRY}/v2/

3) Recreate pods:
     kubectl -n argocd delete pods --all
     kubectl -n argocd get pods -w

EOF
}

case "$COMMAND" in
  print)  cmd_print ;;
  show)   cmd_show ;;
  verify) cmd_verify ;;
  apply)  cmd_apply ;;
  *) die "Unhandled command: ${COMMAND}" ;;
esac
