#!/usr/bin/env bash
# =============================================================================
# 04-configure-containerd-registry.sh
#
# Configure containerd/kubelet on THIS node to pull from a plain-HTTP registry
# such as Zot (e.g. zot-registry:30001).
#
# Symptom this fixes:
#   Failed to pull image "zot-registry:30001/...":
#   Head "https://zot-registry:30001/v2/...": http: server gave HTTP response to HTTPS client
#
# Run on EVERY Kubernetes node (masters and workers), then restart pods:
#   kubectl -n argocd delete pods --all
#
# Usage:
#   sudo ./scripts/04-configure-containerd-registry.sh apply --registry zot-registry:30001
#   sudo ./scripts/04-configure-containerd-registry.sh show --registry zot-registry:30001
#   ./scripts/04-configure-containerd-registry.sh print --registry zot-registry:30001
#
# Commands:
#   apply   Write hosts.toml (+ ensure config_path) and restart containerd
#   show    Show current config for the registry
#   print   Print the hosts.toml that would be written (no root needed)
#   verify  Probe http://REGISTRY/v2/ and check config files exist
#
# Options:
#   --registry HOST:PORT   Registry address (default: zot-registry:30001
#                          or PRIVATE_REGISTRY / ZOT_REGISTRY env)
#   --certs-dir DIR        containerd certs.d root (default: /etc/containerd/certs.d)
#   --config FILE          containerd config.toml (default: /etc/containerd/config.toml)
#   --no-restart           Do not restart containerd after apply
#   --docker               Also add insecure-registries to /etc/docker/daemon.json
#   -h, --help
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

COMMAND=""
REGISTRY="${PRIVATE_REGISTRY:-${ZOT_REGISTRY:-zot-registry:30001}}"
CERTS_DIR="${CONTAINERD_CERTS_DIR:-/etc/containerd/certs.d}"
CONTAINERD_CONFIG="${CONTAINERD_CONFIG:-/etc/containerd/config.toml}"
RESTART=1
CONFIGURE_DOCKER=0

usage() {
  sed -n '2,40p' "$0" | sed 's/^# \?//'
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    apply|show|print|verify) COMMAND="$1"; shift ;;
    --registry)     REGISTRY="$2"; shift 2 ;;
    --certs-dir)    CERTS_DIR="$2"; shift 2 ;;
    --config)       CONTAINERD_CONFIG="$2"; shift 2 ;;
    --no-restart)   RESTART=0; shift ;;
    --docker)       CONFIGURE_DOCKER=1; shift ;;
    -h|--help)      usage ;;
    *) die "Unknown argument: $1 (use --help)" ;;
  esac
done

[[ -n "$COMMAND" ]] || die "Command required: apply|show|print|verify"
REGISTRY="${REGISTRY#http://}"
REGISTRY="${REGISTRY#https://}"
REGISTRY="${REGISTRY%/}"

HOSTS_DIR="${CERTS_DIR}/${REGISTRY}"
HOSTS_FILE="${HOSTS_DIR}/hosts.toml"

hosts_toml_contents() {
  cat <<EOF
# Generated by 04-configure-containerd-registry.sh
# Allow kubelet/containerd to pull from plain-HTTP Zot at ${REGISTRY}

server = "http://${REGISTRY}"

[host."http://${REGISTRY}"]
  capabilities = ["pull", "resolve", "push"]
  skip_verify = true
EOF
}

ensure_config_path() {
  [[ -f "$CONTAINERD_CONFIG" ]] || {
    warn "containerd config not found at ${CONTAINERD_CONFIG}; writing hosts.toml only"
    return 0
  }

  # Prefer CRI registry config_path (containerd 1.5+ / 2.x)
  if grep -qE 'config_path\s*=' "$CONTAINERD_CONFIG"; then
    local current
    current="$(awk -F'=' '/config_path/ {gsub(/[ "'\''\t]/, "", $2); print $2; exit}' "$CONTAINERD_CONFIG" || true)"
    if [[ -n "$current" && "$current" != "$CERTS_DIR" ]]; then
      warn "containerd config_path is '${current}' (expected ${CERTS_DIR})"
      warn "Either pass --certs-dir ${current} or update config.toml to:"
      warn "  config_path = \"${CERTS_DIR}\""
    else
      info "containerd config_path already set (${current:-ok})"
    fi
    return 0
  fi

  info "Adding registry config_path to ${CONTAINERD_CONFIG}"
  # Append a minimal snippet. Operators with heavily customized config.toml
  # should merge this manually if containerd fails to start.
  cat >>"$CONTAINERD_CONFIG" <<EOF

# Added by 04-configure-containerd-registry.sh for HTTP registry ${REGISTRY}
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "${CERTS_DIR}"
EOF
}

configure_docker_insecure() {
  local daemon_json="/etc/docker/daemon.json"
  info "Ensuring Docker insecure-registries includes ${REGISTRY}"
  if ! command -v python3 >/dev/null 2>&1; then
    warn "python3 not found; write ${daemon_json} manually with insecure-registries: [\"${REGISTRY}\"]"
    return 0
  fi
  python3 - <<PY
import json, os
path = "${daemon_json}"
data = {}
if os.path.exists(path):
    with open(path) as f:
        try:
            data = json.load(f) or {}
        except Exception:
            data = {}
regs = data.get("insecure-registries") or []
if "${REGISTRY}" not in regs:
    regs.append("${REGISTRY}")
data["insecure-registries"] = regs
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
print(f"updated {path}: insecure-registries={regs}")
PY
  if command -v systemctl >/dev/null 2>&1; then
    systemctl restart docker || warn "Failed to restart docker; restart manually"
  fi
}

restart_containerd() {
  if [[ "$RESTART" -ne 1 ]]; then
    warn "Skipping containerd restart (--no-restart). Restart manually before deleting pods."
    return 0
  fi
  info "Restarting containerd"
  if command -v systemctl >/dev/null 2>&1; then
    systemctl restart containerd
    systemctl is-active --quiet containerd && info "containerd is active" \
      || warn "containerd may not be active; check: systemctl status containerd"
  else
    warn "systemctl not available; restart containerd manually"
  fi
}

cmd_print() {
  hosts_toml_contents
  echo
  echo "# Target path: ${HOSTS_FILE}"
}

cmd_show() {
  info "Registry: ${REGISTRY}"
  info "Expected hosts file: ${HOSTS_FILE}"
  if [[ -f "$HOSTS_FILE" ]]; then
    echo "---- ${HOSTS_FILE} ----"
    cat "$HOSTS_FILE"
  else
    warn "hosts.toml not found"
  fi
  if [[ -f "$CONTAINERD_CONFIG" ]]; then
    echo "---- config_path in ${CONTAINERD_CONFIG} ----"
    grep -nE 'config_path|registry' "$CONTAINERD_CONFIG" | head -40 || true
  fi
}

cmd_verify() {
  local url="http://${REGISTRY}/v2/"
  info "Probing ${url}"
  local code
  code="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 5 "$url" 2>/dev/null || echo down)"
  info "HTTP ${code} (200 or 401 means the registry is reachable over HTTP)"
  [[ -f "$HOSTS_FILE" ]] && info "hosts.toml present" || warn "hosts.toml missing: ${HOSTS_FILE}"
  if command -v ctr >/dev/null 2>&1; then
    info "Test pull with ctr (optional):"
    echo "  ctr -n k8s.io images pull --plain-http ${REGISTRY}/argoproj/argocd:v3.5.0"
  fi
}

cmd_apply() {
  [[ "$(id -u)" -eq 0 ]] || die "apply must run as root (sudo)"

  info "Configuring containerd for plain-HTTP registry ${REGISTRY}"
  mkdir -p "$HOSTS_DIR"
  hosts_toml_contents >"$HOSTS_FILE"
  info "Wrote ${HOSTS_FILE}"
  ensure_config_path
  if [[ "$CONFIGURE_DOCKER" -eq 1 ]]; then
    configure_docker_insecure
  fi
  restart_containerd

  section "Next steps (on the control plane)"
  cat <<EOF

1) Repeat on EVERY node:
     sudo ./scripts/04-configure-containerd-registry.sh apply --registry ${REGISTRY}

2) Confirm registry is reachable from nodes:
     curl -sS -o /dev/null -w '%{http_code}\\n' http://${REGISTRY}/v2/

3) Recreate Argo CD pods so kubelet retries pulls over HTTP:
     kubectl -n argocd delete pods --all

4) Watch:
     kubectl -n argocd get pods -w

EOF
}

case "$COMMAND" in
  print)  cmd_print ;;
  show)   cmd_show ;;
  verify) cmd_verify ;;
  apply)  cmd_apply ;;
  *) die "Unhandled command: ${COMMAND}" ;;
esac
